CREATE TABLE "User"(
    ID_USER SERIAL PRIMARY KEY, 
    NAME TEXT NOT NULL, 
    FIRSTNAME TEXT NOT NULL, 
    ADDRESS VARCHAR(100) NOT NULL, 
    MAIL TEXT NOT NULL UNIQUE
);

CREATE TABLE "State"(
    ID_STATE SERIAL PRIMARY KEY, 
    TITLE TEXT NOT NULL
);

CREATE TABLE "Equipment"(
    ID_EQUIPMENT SERIAL PRIMARY KEY, 
    TITLE TEXT NOT NULL,
    ID_STATE INT REFERENCES "State" (ID_STATE) ON DELETE CASCADE ON UPDATE CASCADE, 
    ID_USER INT REFERENCES "User" (ID_USER) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE "Notification"(
    ID_NOTIFICATION SERIAL PRIMARY KEY, 
    TIME TIMESTAMP NOT NULL,
    MESSAGE TEXT NOT NULL, 
    ID_EQUIPMENT INT REFERENCES "Equipment" (ID_EQUIPMENT) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO "User" (NAME, FIRSTNAME, ADDRESS, MAIL) VALUES ( 'LeBricoleur', 'Bob', '28 rue de Londre, Paris', 'bob.lebricoleur@gmail.com');
INSERT INTO "State" (TITLE) VALUES ('Open'), ('Close');
INSERT INTO "Equipment" (TITLE, ID_STATE, ID_USER) VALUES ('Fenetre de la cuisine', 1, 1), ('Porte d entrée', 2, 1);
INSERT INTO "Notification" (TIME, MESSAGE, ID_EQUIPMENT) VALUES ('2019-12-02 12:05:12', 'Votre fenetre à été ouverte !', 1);
